import { storage_get, storage_remove, storage_set } from './storage'

export const LANG: 'ja' | 'en' = (() => {
  const saved = storage_get('ug2_lang')
  if (saved === 'ja' || saved === 'en') return saved
  const language = (navigator.language || '').toLowerCase()
  if (!language) return 'ja'
  return language.startsWith('ja') ? 'ja' : 'en'
})()

export function lang_set(value: string): void {
  if (value === 'ja' || value === 'en') storage_set('ug2_lang', value)
  else storage_remove('ug2_lang')
  location.reload()
}

export function lang_saved(): string {
  return storage_get('ug2_lang') || ''
}

const EN: Record<string, string> = {
  'かく': 'Draw',
  'ぬる': 'Fill',
  'けしごむ': 'Eraser',
  'ペン': 'Pen',
  'ぬりつぶし': 'Fill',
  'きりぬき': 'Select',
  'もじ': 'Text',
  '図形': 'Shapes',
  'マーク': 'Marks',
  'マーク(スタンプ)': 'Marks (stamps)',
  'いろ': 'Color',
  'いろをえらぶ': 'Pick a color',
  'いろ（タップで切替）': 'Color (tap to switch)',
  'ふとさ': 'Size',
  'ふとい': 'Bold',
  'ふとさ（タップで切替）': 'Size (tap to switch)',
  'もよう': 'Pattern',
  'もどす': 'Undo',
  'もどす (Ctrl+Z)': 'Undo (Ctrl+Z)',
  'やりなおす (Ctrl+Y)': 'Redo (Ctrl+Y)',
  'いまのどうぐ': 'Current tool',
  'ほかのどうぐ': 'More tools',
  'ツールのせってい': 'Tool settings',
  '手ぶれ補正': 'Stabilizer',
  'フチドリ': 'Outline',
  'フチの色': 'Outline color',
  '不透明度': 'Opacity',
  'ペンのしゅるい': 'Pen type',
  '筆箱（つかえるどうぐ）': 'Pencil case (available tools)',
  '初級筆箱': 'Basic pencil case',
  '上級筆箱': 'Full pencil case',
  '初級はよく使う7つだけ。あとからいつでも切りかえOK': 'Basic keeps just 7 common tools. Switch anytime.',
  '中を塗りつぶす': 'Fill inside',
  'オンにすると、タップした色とおなじ色をレイヤー全体でまとめて塗りかえます': 'When on, fills every area of the tapped color across the layer',
  'へんけい': 'Transform',
  'はんい': 'Selection',
  'はんてん': 'Flip',
  'はんいの中をドラッグすると動かせます（回転・拡大も）': 'Drag inside the selection to move (rotate/scale too)',
  'はんいを削除': 'Delete selection',
  '変形リセット': 'Reset transform',
  '左右反転': 'Flip horizontal',
  '上下反転': 'Flip vertical',
  '左に90°': 'Rotate 90° left',
  '右に90°': 'Rotate 90° right',
  '確定 (Enter)': 'Apply (Enter)',
  'キャンセル (Esc)': 'Cancel (Esc)',
  'コピー': 'Copy',
  '複製': 'Duplicate',
  '削除': 'Delete',
  'クリア': 'Clear',
  '適用': 'Apply',
  '追加': 'Add',
  '移動': 'Move',
  '大きさ': 'Size',
  'つよさ': 'Strength',
  'うごき': 'Motion',
  'かたち': 'Shape',
  'かたち（比率）': 'Shape (aspect)',
  'きれいさ': 'Quality',
  'きれいさ（画質）': 'Quality',
  '画質': 'Quality',
  '比率': 'Aspect',
  '画面の形': 'Screen shape',
  '枚数': 'Count',
  'たて書き': 'Vertical',
  'ふくろ文字': 'Outlined text',
  'もじを入れる': 'Add text',
  'フォント': 'Font',
  'ゴシック': 'Sans',
  '明朝': 'Serif',
  '等幅': 'Mono',
  'まるゴシック（標準）': 'Rounded sans (default)',
  'ドットフォント(くっきり)': 'Dot font (crisp)',
  '＋取込': '+ Import',
  'フォントを取り込んだよ（このセッションの間つかえます）': 'Font imported (available for this session)',

  'コマ': 'Frame',
  'コマを追加': 'Add frame',
  'コマを追加 (N)': 'Add frame (N)',
  'コマ追加': 'Add frame',
  'コマを複製 (D)': 'Duplicate frame (D)',
  'いまのコマを削除': 'Delete current frame',
  'コマ番号（タップでジャンプ）': 'Frame number (tap to jump)',
  'コマ移動': 'Move frame',
  'まえのコマ': 'Previous frame',
  'つぎのコマ': 'Next frame',
  '前のコマ': 'Previous frame',
  '次のコマ': 'Next frame',
  'さいしょのコマへ': 'Go to first frame',
  'ループ再生': 'Loop playback',
  'ループを解除': 'Disable loop',
  'さいせい': 'Play',
  '再生/停止 (Space)': 'Play/Stop (Space)',
  'はやさ': 'Speed',
  'ループ': 'Loop',
  'A-B区間ループ': 'A-B loop',
  'A-Bループを解除': 'Clear A-B loop',
  '3コマ以上のはんいでつかってね': 'Needs a range of 3+ frames',
  'このコマの表示': 'This frame',
  'このコマの表示時間': 'Frame duration',
  'コマを複製': 'Duplicate frame',
  'コマ一覧を閉じる': 'Hide frame list',
  'コマ一覧を開く': 'Show frame list',
  'コマ操作': 'Frame actions',
  'このコマをのばす': 'Hold this frame',
  '1コマぶん〜8コマぶん のばせます': 'Hold for 1 to 8 frames',
  'ホールド一括': 'Set hold for all',
  'ホールドをそろえました（もどす不可）': 'Holds unified (can\'t undo)',
  '全コマを': 'All frames',
  'まとめて追加': 'Add multiple',
  '番号ジャンプ': 'Jump to number',
  'タイムラインをたたむ': 'Collapse timeline',
  'これ以上コマを増やせないよ': 'Can\'t add more frames',
  '上限で一部だけ足したよ': 'Hit the limit, added some',
  '逆順にしました': 'Reversed',
  '往復にしました': 'Ping-pong applied',
  '往復＝1,2,3 → 1,2,3,2 みたいにピンポンさせるよ。': 'Ping-pong turns 1,2,3 into 1,2,3,2.',

  'レイヤー': 'Layers',
  'レイヤー切替': 'Switch layer',
  'いまのレイヤーを下と結合': 'Merge layer down',
  'いまのレイヤーを他へコピー': 'Copy layer to another',
  'いまのレイヤーを消去': 'Clear this layer',
  'レイヤーを消しました': 'Layer cleared',
  '表示': 'View',
  'ぜんたい': 'Overview',
  '全体表示 (0)': 'Fit to screen (0)',
  '表示を左右反転(確認用)': 'Mirror view (for checking)',
  '左右反転で確認': 'Check mirrored',
  'オニオン': 'Onion',
  'オニオンスキン': 'Onion skin',
  'オニオンスキンの枚数': 'Onion skin count',
  'まえのコマをうすく見る': 'Show previous frames faintly',
  'まえ後の枚数': 'Frames before/after',
  'グリッド': 'Grid',
  'マス目': 'Grid',
  'マス': 'cells',
  'グリッドの大きさ': 'Grid size',
  '紙の色': 'Paper color',
  '紙のいろ': 'Paper color',
  '全コマ共通': 'Shared by all frames',

  'メニュー': 'Menu',
  'ノート': 'Note',
  '新規': 'New',
  '新しいノート': 'New note',
  '開く': 'Open',
  '開く(.ugn2)': 'Open (.ugn2)',
  '開く(kwz/ppm)': 'Open (kwz/ppm)',
  'ファイル': 'File',
  'ファイルに保存': 'Save to file',
  'ファイルを開く': 'Open file',
  'スロット': 'Slots',
  '保存スロット': 'Save slots',
  '自動保存': 'Autosave',
  '自動': 'Auto',
  'ここに保存': 'Save here',
  '上書き': 'Overwrite',
  '（空き）': '(empty)',
  '保存したよ': 'Saved',
  '保存する': 'Save',
  '保存に失敗しました…': 'Save failed...',
  '.ugn2に保存しました': 'Saved as .ugn2',
  '開きました': 'Opened',
  '開けなかった…（こわれてるかも）': 'Couldn\'t open... (maybe corrupted)',
  'まえのつづきから再開したよ': 'Resumed from last time',
  '取り込み': 'Import',
  '写真': 'Photo',
  '動画→コマ': 'Video to frames',
  '動画をコマにする': 'Turn video into frames',
  '動画を取り込み中': 'Importing video',
  'PNG連番ZIP': 'PNG sequence ZIP',
  'PNG連番ZIPを書き出し中': 'Exporting PNG sequence ZIP',
  'PNG連番を取り込み中': 'Importing PNG sequence',
  'うごメモ取り込み': 'Import Flipnote',
  '.kwz / .ppm を読み込んで、コマとして取り込みます': 'Loads .kwz / .ppm files as frames',
  'ことば / Language': 'ことば / Language',
  'じどう / Auto': 'じどう / Auto',
  'うごメモ作品を読み込む': 'Load a Flipnote work',
  'うごメモ作品を読み込み中': 'Loading Flipnote work',
  'うごメモ': 'Flipnote',
  'うごメモ3D': 'Flipnote 3D',
  '書き出し': 'Export',
  '書き出しハブ…': 'Export hub...',
  'つくる': 'Create',
  'エフェクト…': 'Effects...',
  'トランジション': 'Transitions',
  'エフェクトはノーマルモード専用だよ': 'Effects are Normal mode only',
  'トランジションはノーマルモード専用だよ': 'Transitions are Normal mode only',
  'おと': 'Sound',
  'せってい': 'Settings',
  'アプリの設定': 'App settings',
  'ダークテーマ': 'Dark theme',
  'テーマ切替': 'Toggle theme',
  'UI効果音': 'UI sounds',
  'チュートリアル': 'Tutorial',
  'つかいかた': 'How to use',
  'キャンバス変更': 'Change canvas',
  'サイズを変更する': 'Change size',
  'いまと同じサイズだよ': 'Same size as now',
  'キャンバスの': 'Canvas',

  'ノーマル': 'Normal',
  'うごメモモード': 'Flipnote DSi mode',
  'うごメモ3Dモード': 'Flipnote 3D mode',
  'いまのモード(メニュー→モードで変更)': 'Current mode (Menu > Mode to change)',
  'いまは': 'Now: ',
  'うごメモ系モードはキャンバスが実機サイズになり、色やレイヤーも実機と同じ制限になります。切りかえるとキャンバスを作りなおすので「もどす」はできません。': 'Flipnote modes use real-hardware canvas size, colors and layer limits. Switching rebuilds the canvas, so undo is not possible.',
  'モードになりました': ' mode',

  'BGM音量': 'BGM volume',
  'SE音量': 'SE volume',
  'SEミキサー': 'SE mixer',
  'SEミキサー（コマ割当）': 'SE mixer (frame assign)',
  '再生中、印のついたコマでSEが鳴るよ。': 'SEs play on marked frames during playback.',
  'ためし聞き': 'Preview',
  'マイク録音': 'Mic recording',
  'アテレコ録音': 'Dub recording',
  '再生しながら録音': 'Record while playing',
  '録音中…もういちど押すと止まるよ': 'Recording... press again to stop',
  '録音中！もういちど押すと止まるよ': 'Recording! Press again to stop',
  'べつのスロットで録音中だよ': 'Already recording on another slot',
  'マイクが使えないみたい…': 'Mic doesn\'t seem available...',
  'BGMを読み込みました': 'BGM loaded',
  'SEを読み込みました': 'SE loaded',
  '読めない形式みたい…': 'Unsupported format...',
  'プリセット…': 'Presets...',

  'マイマーク': 'My marks',
  'じぶんの色': 'My colors',
  '＋とうろく': '+ Register',
  '(いまの色を＋でとうろく／長押しで削除)': '(+ registers current color / long-press deletes)',
  '(タップで配置／長押しで削除)': '(tap to place / long-press to delete)',
  'えらんだマークはキャンバスに配置して、回転・拡大できます': 'Placed marks can be moved, rotated and scaled',
  'キャンバスをタップして位置を決め、✓で確定': 'Tap the canvas to position, confirm with ✓',
  '✓で確定→そのまま連続スタンプ！おわるときはEsc': '✓ to stamp, keep stamping! Esc to finish',
  'マークを消しました': 'Mark deleted',
  '#RRGGBB の形で入れてね': 'Use the #RRGGBB format',
  'スタンダード': 'Standard',

  'GIFを書き出し中': 'Exporting GIF',
  'GIFを書き出しました': 'GIF exported',
  'MP4を書き出し中': 'Exporting MP4',
  'KWZ（うごメモ3D）を書き出し中': 'Exporting KWZ (Flipnote 3D)',
  'PPM（うごメモDSi）を書き出し中': 'Exporting PPM (Flipnote DSi)',
  'PNGを書き出しました': 'PNG exported',
  'PNGを作れなかった…': 'Couldn\'t create PNG...',
  'PNGが入ってないみたい': 'No PNGs found',
  'ZIPを書き出しました': 'ZIP exported',
  'ZIPを読めなかった…': 'Couldn\'t read ZIP...',
  '動画を書き出しました': 'Video exported',
  '動画を作れなかった…': 'Couldn\'t create video...',
  '動画（WebM）を録画中': 'Recording video (WebM)',
  'このブラウザは動画書き出しに対応してないみたい…': 'This browser doesn\'t seem to support video export...',
  'この環境はMP4に未対応。WebMをつかってね': 'MP4 unsupported here. Use WebM',
  'A-B区間だけ（GIF/連番ZIP）': 'A-B range only (GIF/PNG ZIP)',
  'うごメモは色数がすくない形式だから、近い色にまるめられるよ。': 'Flipnote formats have few colors, so colors get rounded to the nearest.',
  '：KWZ書き出しがドットそのままで一番きれいだよ': ': KWZ export keeps pixels 1:1 and looks best',
  '：PPM書き出しがドットそのままで一番きれいだよ': ': PPM export keeps pixels 1:1 and looks best',
  'X・Instagram等へは「共有」から。ダウンロードできない端末でも共有→ファイルに保存が使えます': 'Share to X/Instagram via Share. If downloads don\'t work, use Share > Save to Files',
  '読み込みました': 'Loaded',
  '読み込み': 'Load',
  '読み込めなかった…': 'Couldn\'t load...',
  '読み込めなかった…（.kwz / .ppm の中身を確認してください）': 'Couldn\'t load... (check the .kwz / .ppm file)',
  '画像を読めなかった…': 'Couldn\'t read the image...',
  '画像': 'Image',
  '準備中…': 'Preparing...',
  '背景を透過にする': 'Transparent background',
  '消しました': 'Deleted',
  '複製しました': 'Duplicated',
  '入れる': 'Insert',
  '作成する': 'Create',
  '配置する': 'Place',
  'おわる': 'Finish',
  'やめる': 'Cancel',
  'とじる': 'Close',
  'まえへ': 'Back',
  'すすむ': 'Next',
  'はじめまして！': 'Welcome!',
  'と': ' and ',
  'をえらんでね。': '.',
  'を読み込みます。': ' will be loaded.',
  'いまのノートは': 'The current note ',
  '置きかわります': 'will be replaced',
  'この操作は「もどす」できない': 'This can\'t be undone',
  'この操作は「もどす」できません': 'This can\'t be undone',
  'あとから ☰メニュー →「キャンバス」でも変えられるよ。': 'You can change it later from Menu > Canvas.',
  'ドラッグで位置、ボタンで回転・大きさ、✓で決定': 'Drag to move, buttons rotate/scale, ✓ to confirm',

  '作品情報': 'Work info',
  'プロジェクト': 'Project',
  'なまえ（作者3世代）': 'Names (3 author generations)',
  '作者ID': 'Author ID',
  '現在': 'Current',
  '現IDのリージョン判定:': 'Region of current ID:',
  'PPM=16桁hex（先頭0/1=日本, 5=米, 9=欧）/ KWZ=20桁hex': 'PPM = 16-hex (lead 0/1=JP, 5=US, 9=EU) / KWZ = 20-hex',
  'ファイル名履歴': 'Filename history',
  '現在の名前は書き出し時に実機法則で更新されるよ': 'The current name updates to the real-hardware rule on export',
  '編集履歴（世代）': 'Edit history (generations)',
  'この編集を新しい世代にする（現→親へ繰り下げ）': 'Make this a new generation (current becomes parent)',
  '世代を繰り下げました': 'Generation shifted',
  'ロック（本人以外編集不可）': 'Lock (only the author can edit)',
  'コメント属性（flags bit4）': 'Comment attribute (flags bit4)',
  '属性': 'Attributes',
  '作品情報を保存しました': 'Work info saved',
  'ようこそ！': 'Welcome!',
  'ここがキャンバス。指やペンでそのまま描けるよ。2本指でズームと移動。': 'This is the canvas. Draw with your finger or pen. Two fingers to zoom and pan.',
  'どうぐ': 'Tools',
  'スマホは下のドック、PCは左のバー。ペンをもう一度タップすると、ペンの種類（大きな筆先えらび）と太さが出るよ。': 'Dock at the bottom on phones, bar on the left on PC. Tap the pen again for pen types and size.',
  'グリッドの大きさ・オニオンの枚数・テーマ・筆箱（初級/上級）はここ。むずかしければ初級筆箱にしてみてね。': 'Grid size, onion count, theme, pencil case (basic/full) live here. Try the basic case if it feels busy.',
  'ここでパレットを開く。「＋とうろく」でじぶんの色も保存できる。': 'Open the palette here. Register your own colors with +.',
  'A・B・Cの3枚＋写真レイヤー。順番の入れかえや透けぐあいもここ。': 'Layers A, B, C plus a photo layer. Reorder and set opacity here.',
  '再生': 'Playback',
  '▶で動かしてみよう。スペースキーでもOK。となりはループとA-B区間ループ。': 'Press ▶ to play (Space works too). Next to it: loop and A-B loop.',
  'タイムライン': 'Timeline',
  'コマの一覧。タップで移動、長おしでつかんで並べかえ。右クリックでメニューも。': 'Your frames. Tap to jump, long-press to reorder. Right-click for a menu.',
  '＋で新しいコマ。オニオンスキン（右上）でまえのコマがうっすら見えるよ。': '+ adds a frame. Onion skin (top right) shows previous frames faintly.',
  'ホールド': 'Hold',
  'このコマを何コマぶん見せるか。タメをつくるのに便利！［ ］キーでも変えられる。': 'How many frames this one stays. Great for timing! [ and ] keys work too.',
  'A-Bループ': 'A-B loop',
  '気になるところだけくり返し再生。コマを右クリック→「ここからループA」でも設定できるよ。': 'Loop just the part you\'re working on. Right-click a frame to set loop A.',
  'GIF・MP4・WebMのほか、うごメモのKWZ/PPMにも書き出せる！': 'Export GIF, MP4, WebM, and even Flipnote KWZ/PPM!',
  'おしまい！': 'That\'s it!',
  'また見たくなったらここから。たのしんで描いてね〜': 'Reopen this tour here anytime. Have fun drawing!',
  'はじめる！': 'Let\'s go!',
  'つぎへ': 'Next',
  '自由に描ける拡張モード': 'Free-drawing extended mode',
  'DSi風・2レイヤー・実機準拠': 'DSi style, 2 layers, hardware-accurate',
  '3DS風・3レイヤー・6色': '3DS style, 3 layers, 6 colors',
  '2レイヤー・3色に量子化するよ': 'Quantizes to 2 layers, 3 colors',
  '3レイヤー・6色に量子化するよ': 'Quantizes to 3 layers, 6 colors',
  'モードをえらぶ': 'Choose a mode',
  'モードへ': ' mode',
  '切りかえる': 'Switch',
  '作りかえる': 'Rebuild',
  '実行する': 'Run',
  '取り込む': 'Import',
  '読み込む': 'Load',
  'はじめる': 'Start',
  '消す': 'Delete',
  'なし': 'None',
  'ドット': 'px',
  ' ドット': ' px',
  'キャンバス: ': 'Canvas: ',
  'キャンバスを <b>': 'Rebuild the canvas to <b>',
  '</b> に作りかえて、': '</b> and match ',
  'の制限（色・レイヤー）にそろえるよ。<br><b>この操作は「もどす」できない</b>（履歴は消えるよ）。': ' restrictions (colors/layers).<br><b>This can\'t be undone</b> (history is cleared).',
  ' に作りかえるよ。<br><b>この操作は「もどす」できない</b>（履歴は消えるよ）。': '.<br><b>This can\'t be undone</b> (history is cleared).',
  '全部のコマにかかるよ。<br><b>この操作は「もどす」できない</b>（履歴は消えるよ）。': 'Applies to every frame.<br><b>This can\'t be undone</b> (history is cleared).',
  'あたらしいノート！': 'New note!',
  'むだいのノート': 'Untitled note',
  'ノートの名前': 'Note name',
  'ノートを保存（.ugn2）': 'Save note (.ugn2)',
  'いまのノートは自動保存ぶんだけ残るよ。<br>「': 'The current note only stays in autosave.<br>Open "',
  'いまのノートは自動保存ぶんだけ残るよ。<br>スロットを開く？': 'The current note only stays in autosave.<br>Open slots?',
  '」を開く？': '"?',
  ' いまのノートは自動保存から消えるよ。残したいならスロット保存してからどうぞ。': ' The current note will leave autosave. Save it to a slot first if you want to keep it.',
  'このスロットを消す？（もどせないよ）': 'Delete this slot? (can\'t be undone)',
  'スロットに保存しました': 'Saved to slot',
  '保存に失敗…': 'Save failed...',
  'ようこそ！ さいしょの設定': 'Welcome! First-time setup',
  'できあがり！': 'Done!',
  'コマへジャンプ': 'Jump to frame',
  '何コマ目にとぶ？（1〜': 'Jump to which frame? (1 to ',
  'コマをコピーしました': 'Frame copied',
  'コピーしたコマがないよ': 'No copied frame yet',
  'うしろに複製': 'Duplicate after',
  'ここからループA': 'Loop A from here',
  'ここまでループB': 'Loop B to here',
  'ループのはじまり: ': 'Loop start: ',
  'ループのおわり: ': 'Loop end: ',
  'コマ目を消すよ。': ' will be deleted.',
  '最後の1枚は消せないよ': 'Can\'t delete the last frame',
  'コマ追加しました': 'Frames added',
  'コマ取り込みました': ' frames imported',
  'コマ読み込みました': ' frames loaded',
  'コマがいっぱいで取り込めないよ': 'Frames are full, can\'t import',
  'コマ数の上限を超えちゃう': 'That would exceed the frame limit',
  'これ以上コマを増やせないよ（最大': 'Can\'t add more frames (max ',
  'コマ（写真レイヤーへ）': ' frames (to photo layer)',
  'コマ）': ' frames)',
  'fps) で切り出して、写真レイヤーに追加するよ。': 'fps) and add them to the photo layer.',
  'いまの「はやさ」(': 'Frames are cut at the current speed (',
  'サイズを変えました': 'Size changed',
  'いどう': 'Move',
  'なげなわ': 'Lasso',
  'はりつけ': 'Paste',
  'スポイト': 'Eyedropper',
  '直線': 'Line',
  '四角': 'Rectangle',
  'まる': 'Circle',
  'ほし': 'Star',
  'ハート': 'Heart',
  '色をスポイトしました ': 'Color picked ',
  '先に選択ツールでコピーしてね': 'Copy with the select tool first',
  '選択範囲': 'Selection',
  'いまのレイヤー全体': 'Whole current layer',
  'レイヤー全体にエフェクトをかけました': 'Effect applied to the layer',
  'しました': ' applied',
  'エフェクト': 'Effects',
  'かける': 'Apply',
  '枚のトランジションを挿入しました（もどす不可）': ' transition frames inserted (can\'t undo)',
  '枚</b>': ' frames</b>',
  'にかかります': ' to finish',
  '逆順にする': 'Reverse',
  '往復にする': 'Ping-pong',
  '全コマを ': 'All frames: ',
  '下のレイヤーと結合しました': 'Merged with the layer below',
  'いちばん下のレイヤーは結合できないよ': 'Can\'t merge the bottom layer',
  'にコピーしました': ' copied',
  'をコピー': ' copy',
  'コピー先…': 'Copy to...',
  '表示/非表示': 'Show/hide',
  '前面へ': 'Bring forward',
  '背面へ': 'Send back',
  '下と結合': 'Merge down',
  '消去': 'Clear',
  '切り取り': 'Cut',
  '左右対称': 'Mirror X',
  '上下対称': 'Mirror Y',
  '左回転': 'Rotate left',
  '右回転': 'Rotate right',
  '筆圧で太さ': 'Pressure size',
  'はなれた同じ色もぜんぶ': 'All matching colors everywhere',
  'とうろくしました': 'Registered',
  'もう登録されてるよ': 'Already registered',
  'まだ登録がありません': 'Nothing registered yet',
  '長押しで削除': 'long-press to delete',
  '選択範囲から登録': 'From selection',
  '画像から登録': 'From image',
  '選択範囲をマークに登録しました': 'Selection registered as a mark',
  '画像をマークに登録しました': 'Image registered as a mark',
  '登録できるものが見つからないよ（レイヤーがからっぽかも）': 'Nothing to register (layer may be empty)',
  'マークの保存に失敗（容量オーバーかも）': 'Couldn\'t save the mark (maybe out of space)',
  '共有（SNSへ）': 'Share (to SNS)',
  'ダウンロード': 'Download',
  'このコマをPNG': 'This frame as PNG',
  '・A-B区間': ' / A-B range',
  '・背景透過': ' / transparent bg',
  '大きいので半分サイズで書き出すよ（': 'Large size, exporting at half size (',
  '実時間で録るよ。だいたい': 'Records in real time. About ',
  '秒まってね。': ' seconds.',
  '実時間キャプチャで録画中…': 'Recording in real time...',
  'H.264でエンコード中…': 'Encoding H.264...',
  'KWZを書き出しました': 'KWZ exported',
  'KWZを作れなかった…': 'Couldn\'t create KWZ...',
  'KWZを書き出し（': 'Export KWZ (',
  'PPMを書き出しました': 'PPM exported',
  'PPMを作れなかった…': 'Couldn\'t create PPM...',
  'PPMを書き出し（': 'Export PPM (',
  'MP4を書き出しました': 'MP4 exported',
  'MP4を作れなかった…': 'Couldn\'t create MP4...',
  'MP4を書き出し（': 'Export MP4 (',
  'アフレコ ': 'Dub ',
  '録音 ': 'Rec ',
  'アフレコをBGMに保存しました': 'Dub saved to BGM',
  '録音を保存しました': 'Recording saved',
  '録音を保存できなかった…': 'Couldn\'t save the recording...',
  '再生にあわせてマイクで録音して、空いてるBGMスロットに入れるよ。': 'Records the mic along with playback into a free BGM slot.',
  '作品情報…': 'Work info...',
  '作品情報（実機ヘッダ）': 'Work info (hardware header)',
  '現ID': 'Current ID',
  '親ID': 'Parent ID',
  '親作品': 'Parent work',
  '親作者': 'Parent author',
  '編集もとの作者': 'Original author',
  'さいしょの作者': 'First author',
  'いまの作者（あなた）': 'Current author (you)',
  '編集者': 'Editor',
  '現: ': 'Now: ',
  '親: ': 'Parent: ',
  '元: ': 'Root: ',
  'つくった日: ': 'Created: ',
  '編集': 'Edits: ',
  '（書き出し時に生成）': '(generated on export)',
  '（未対応）': '(unsupported)',
  'エラー: ': 'Error: ',
  'エラー(async): ': 'Error (async): ',
  'なにかおかしいかも': 'Something looks off',
  '動画を読めなかった…': 'Couldn\'t read the video...',
  'いまは<b>うごメモ3Dモード</b>': 'Now in <b>Flipnote 3D mode</b>',
  'いまは<b>うごメモモード</b>': 'Now in <b>Flipnote DSi mode</b>',
  'いまのコマ（': 'Current frame (',
  '#app が見つからないよ': '#app not found',
  '絵の拡大・縮小': 'Scale artwork',
  '対象': 'Target',
  'ぜんぶ': 'All layers',
  'いまのレイヤー': 'Current layer',
  'かくだい': 'Scale',
  'かくだい・しゅくしょう': 'Scale artwork',
  'ばいりつ': 'Scale',
  'かくてい': 'Apply',
  '絵を拡大縮小しました': 'Artwork scaled',
  'うごかす': 'Move & rotate',
  'うごかす（スライド・かいてん・かくだい）': 'Move, rotate & scale',
  'よこ': 'X',
  'たて': 'Y',
  'かいてん': 'Rotate',
  '絵をうごかしました': 'Artwork transformed',
  '画像からうごメモ': 'Image to Flipnote',
  '画像を実機の色とレイヤーへ変換し、PPM・KWZ用ノートを作ります': 'Convert an image to hardware colors and layers for a PPM or KWZ note',
  '画像からうごメモを作る': 'Create Flipnote from image',
  '通常の写真取り込みとは別に、実機の色・レイヤー制限へ合わせた編集可能なノートを作ります。いまのノートは置きかわります。': 'Creates an editable note under the hardware color and layer limits, separately from normal photo import. The current note will be replaced.',
  '形式': 'Format',
  '配置': 'Fit',
  'なめらかさ': 'Smoothness',
  '画像から自動': 'Auto from image',
  '画面いっぱい': 'Fill screen',
  '画像全体': 'Show whole image',
  '1コマ・静止': '1 frame · still',
  '4コマ・軽量': '4 frames · light',
  '8コマ・標準': '8 frames · standard',
  '16コマ・最高': '16 frames · best',
  '明暗': 'Contrast',
  '色の強さ': 'Saturation',
  'このノートを作る': 'Create this note',
  '変換を準備中…': 'Preparing conversion...',
  '実機の色へ変換中…': 'Converting to hardware colors...',
  '画像を準備できませんでした': 'Could not prepare the image',
  '変換できませんでした': 'Conversion failed',
  'プレビューを準備できませんでした': 'Could not prepare the preview',
  'PPM用のうごメモノートを作りました': 'Created a Flipnote note for PPM',
  'KWZ用のうごメモ3Dノートを作りました': 'Created a Flipnote 3D note for KWZ',
  'ノートを作れませんでした…': 'Could not create the note...',
  'PPM・うごメモ': 'PPM · Flipnote',
  'KWZ・うごメモ3D': 'KWZ · Flipnote 3D',
  'ノートだけ作る': 'Create note only',
  '作って書き出す…': 'Create and export...',
  '白': 'White',
  '黒': 'Black',
  '赤': 'Red',
  '黄': 'Yellow',
  '緑': 'Green',
  '青': 'Blue',
  '<b>PPM</b>　256×192・紙1色＋固定インク2色・描画2レイヤー。複数コマの時間ディザで写真の階調を補います。': '<b>PPM</b> 256×192 · one paper color + two fixed inks · two drawing layers. Temporal dithering across frames restores photographic tones.',
  '<b>KWZ</b>　編集310×230・ファイル320×240・全6色。赤・緑・青を含む色を3レイヤーへ2色ずつ割り当てます。': '<b>KWZ</b> 310×230 editing area · 320×240 file frame · all six colors. Colors including red, green and blue are assigned as two inks on each of three layers.',

}

export function tr(s: string): string {
  return LANG === 'en' ? (EN[s] ?? s) : s
}

let sorted: string[] | null = null

export function tr_html(html: string): string {
  if (LANG !== 'en') return html
  if (!sorted) sorted = Object.keys(EN).sort((a, b) => b.length - a.length)
  let out = html
  for (const k of sorted) {
    if (out.indexOf(k) >= 0) out = out.split(k).join(EN[k])
  }
  return out
}

export function tr_dom(root: HTMLElement): void {
  if (LANG !== 'en') return
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
  let n = walker.nextNode()
  while (n) {
    const t = (n.nodeValue || '').trim()
    if (t && EN[t]) n.nodeValue = (n.nodeValue || '').replace(t, EN[t])
    n = walker.nextNode()
  }
  for (const el of root.querySelectorAll<HTMLElement>('[title], [placeholder], [aria-label]')) {
    for (const at of ['title', 'placeholder', 'aria-label']) {
      const v = el.getAttribute(at)
      if (v) {
        const w = EN[v] || tr_line(v)
        if (w !== v) el.setAttribute(at, w)
      }
    }
  }
}

function tr_line(s: string): string {
  if (!sorted) sorted = Object.keys(EN).sort((a, b) => b.length - a.length)
  let out = s
  for (const k of sorted) if (out.indexOf(k) >= 0) out = out.split(k).join(EN[k])
  return out
}
